### ISSUE TITLE
what is the license of this repository?

### ISSUE THREAD

**Issue by amirhabibzadeh** [uideck/play-bootstrap#1]
Hi,

There is no license specified in this repo and As i read your readme and description, I think MIT, GPL3 is what you need.
If possible please add license.

Regards
Amir

**Comment by Musharofchy** [comment]
Hey Amir, yes you are right. Its MIT, GPL3

**Comment by amirhabibzadeh** [comment]
Hey @Musharofchy , so please add one of them to repository like this doc: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
